### ISSUE TITLE
Users marked as spammers by admins end up in the whitelist

### ISSUE THREAD

**Issue by dsent** [umputun/tg-spam#183]
I've noticed this pattern just recently, but all users either banned by the bot, or manually, end up in the whitelist anyway.
It's not a critical issue, as they're banned in the group itself, but the whitelist is getting enormous and unmanageable.
I understand that this is probably the way "not checking more than the required number of messages" policy is implemented, but still, I believe it's not necessary for detected spammers 🤔

**Comment by umputun** [comment]
I'm a little bit puzzled about this one. The whitelist is a SQLite table named "approved_users," and I don't see any detected spammers here. There is a table for "detected_spam," which is needed for the UI. Is this the one you meant? If this is the case, it can be capped with a reasonable limit because the UI doesn't use anything outside of the last 500 records.

**Comment by dsent** [comment]
All spammers end up in approved_users for me.

**Comment by umputun** [comment]
ah, probably something to do with the soft-ban, will take a look at it.

**Comment by umputun** [comment]
hmm, can't reproduce it. Running with those params: `--telegram.group=******* --telegram.token=***** --admin.group=******  --dbg --min-msg-len=20 --server.enabled --server.auth=passwd --meta.links-limit=2 --meta.image-only --min-probability=80 --soft-ban`

I see the expected behavior: the detected spam is added to the `detected_spam` table, and the check results go to the `spam` table. Some meta info about the message is added to the "locator" table as well (`messages`). However, nothing was added to `approved_users`, neither on detection nor on ban confirmation.

**Comment by dsent** [comment]
Ok, it seems that only users banned manually by replying "spam" to their messages, end up in the approved_users.

**Comment by umputun** [comment]
> Ok, it seems that only users banned manually by replying "spam" to their messages, end up in the approved_users.

this makes sense. Those users are approved already because they passed all the spam checks. Probably they are not getting removed from approved list on the manual ban.

**Comment by umputun** [comment]
The issue was related to an unexpected side effect from the innocent-looking OnMessage call. This function is primarily used to process the incoming message, but as part of the admin's spam processor, it is used to get the status of checks. However, it is not just checking the status but also updates approved users if the checks pass.

To fix it, I have added an explicit parameter set by "info only" function calls.

Pls, try this branch (image: `umputun/tg-spam:fix-183`) before the merge. I have tested it with automatic tests as well as manually, but just in case ...
