### ISSUE TITLE
Can't confirm bans for messages without text

### ISSUE THREAD

**Issue by dsent** [umputun/tg-spam#198]
Every time I try to confirm bans for messages with no text (blocked by one of the meta checks), I get this: `error: failed confirmation ban: failed to get clean message: no original message found in callback msgsData`. The problem is probably that the messages are internally identified by their text. But this doesn't have to be that way for the messages with buttons created by the bot itself.

Can we embed some kind of ID to the buttons, so the message doesn't have to be identified by the text, if it's created by the bot itself, not forwarded to the admin group?

**Comment by dsent** [comment]
This way, we can also avoid ambiguity in case that different users send exactly the same message. Having the same text, they will have different internal IDs.

**Comment by umputun** [comment]
This is not the accurate assumption of how it is currently working. Both message ID and user ID have already been passed in; see https://github.com/umputun/tg-spam/blob/40c3b74eec0b59bd5a897f96876f707c4f19f543/app/events/admin.go#L706-L706.

The issue is about a different thing—failed text extraction should not fail the confirmation flow. 

The reason we need to extract this text and not just use msg_id from the callbackData is the ability to handle admin reports made not just by the `/spam` reply but also by the admin's forwarding. I don't recall why exactly, but I believe in this case TG doesn't keep the ID of the original message, and matching on text was the only way to find the original.

**Comment by umputun** [comment]
The ticket was closed automatically by PR, but please give it a try and confirm. I think it will work the way you expected, as the change was rather trivial.
